require('./docker_start');
require('./create-test-db');
// require('./sip-gateways');
// require('./smpp-gateways');
// require('./service-providers');
// require('./voip-carriers');
// require('./accounts');
// require('./phone-numbers');
// require('./applications');
// require('./auth');
// require('./sbcs');
// require('./ms-teams');
// require('./speech-credentials');
// require('./recent-calls');
// require('./users');
// require('./login');
// require('./webapp_tests');
// // require('./homer');
// require('./call-test');
// require('./password-settings');
// require('./email_utils');
// require('./system-information');
// require('./lcr-carriers-set-entries');
// require('./lcr-routes');
// require('./lcrs');
require('./tts-cache');
require('./docker_stop');
