module.exports = [
  { name: 'Arabic, Gulf', value: 'ar-AE' },
  { name: 'Arabic, Modern Standard', value: 'ar-SA' },
  { name: 'Afrikaans', value: 'af-ZA' },
  { name: 'Basque', value: 'eu-ES' },
  { name: 'Catalan', value: 'ca-ES' },
  { name: 'Chinese, Simplified', value: 'zh-CN' },
  { name: 'Chinese, Traditional', value: 'zh-TW' },
  { name: 'Chinese (Cantonese), Hong-Kong', value: 'zh-HK' },
  { name: 'Croatian', value: 'hr-HR' },
  { name: 'Czech', value: 'cs-CZ' },
  { name: 'Danish', value: 'da-DK' },
  { name: 'Dutch', value: 'nl-NL' },
  { name: 'Australian English', value: 'en-AU' },
  { name: 'British English', value: 'en-GB' },
  { name: 'US English', value: 'en-US' },
  { name: 'Indian English', value: 'en-IN' },
  { name: 'Irish English', value: 'en-IE' },
  { name: 'New Zealand English', value: 'en-NZ' },
  { name: 'Scottish English', value: 'en-AB' },
  { name: 'South African English', value: 'en-ZA' },
  { name: 'Welsh English', value: 'en-WL' },
  { name: 'Farsi', value: 'fa-IR' },
  { name: 'Finnish', value: 'fi-FI' },
  { name: 'French', value: 'fr-FR' },
  { name: 'Canadian French', value: 'fr-CA' },
  { name: 'Galician', value: 'gl-ES' },
  { name: 'German', value: 'de-DE' },
  { name: 'Swiss German', value: 'de-CH' },
  { name: 'Greek', value: 'el-GR' },
  { name: 'Hindi', value: 'hi-IN' },
  { name: 'Hebrew', value: 'he-IL' },
  { name: 'Italian', value: 'it-IT' },
  { name: 'Indian Hindi', value: 'hi-IN' },
  { name: 'Indonesian', value: 'id-ID' },
  { name: 'Japanese', value: 'ja-JP' },
  { name: 'Korean', value: 'ko-KR' },
  { name: 'Latvian', value: 'lv-LV' },
  { name: 'Malay', value: 'ms-MY' },
  { name: 'Norwegian Bokmål', value: 'no-NO' },
  { name: 'Polish', value: 'pl-PL' },
  { name: 'Portuguese', value: 'pt-PT' },
  { name: 'Brazilian Portuguese', value: 'pt-BR' },
  { name: 'Romanian', value: 'ro-RO' },
  { name: 'Russian', value: 'ru-RU' },
  { name: 'Serbian', value: 'sr-RS' },
  { name: 'Slovak', value: 'sk-SK' },
  { name: 'Somali', value: 'so-SO' },
  { name: 'Spanish', value: 'es-ES' },
  { name: 'US Spanish', value: 'es-US' },
  { name: 'Swedish', value: 'sv-SE' },
  { name: 'Tagalog/Filipino', value: 'tl-PH' },
  { name: 'Thai', value: 'th-TH' },
  { name: 'Ukrainian', value: 'uk-UA' },
  { name: 'Vietnamese', value: 'vi-VN' },
  { name: 'Zulu', value: 'zu-ZA' }
];
