module.exports = [
  { name: 'Afrikaans (South Africa)', value: 'af-ZA' },
  { name: 'Albanian (Albania)', value: 'sq-AL' },
  { name: 'Amharic (Ethiopia)', value: 'am-ET' },
  { name: 'Arabic (Algeria)', value: 'ar-DZ' },
  { name: 'Arabic (Bahrain)', value: 'ar-BH' },
  { name: 'Arabic (Egypt)', value: 'ar-EG' },
  { name: 'Arabic (Iraq)', value: 'ar-IQ' },
  { name: 'Arabic (Israel)', value: 'ar-IL' },
  { name: 'Arabic (Jordan)', value: 'ar-JO' },
  { name: 'Arabic (Kuwait)', value: 'ar-KW' },
  { name: 'Arabic (Lebanon)', value: 'ar-LB' },
  { name: 'Arabic (Morocco)', value: 'ar-MA' },
  { name: 'Arabic (Oman)', value: 'ar-OM' },
  { name: 'Arabic (Qatar)', value: 'ar-QA' },
  { name: 'Arabic (Saudi Arabia)', value: 'ar-SA' },
  { name: 'Arabic (State of Palestine)', value: 'ar-PS' },
  { name: 'Arabic (Tunisia)', value: 'ar-TN' },
  { name: 'Arabic (United Arab Emirates)', value: 'ar-AE' },
  { name: 'Armenian (Armenia)', value: 'hy-AM' },
  { name: 'Azerbaijani (Azerbaijan)', value: 'az-AZ' },
  { name: 'Basque (Spain)', value: 'eu-ES' },
  { name: 'Bengali (Bangladesh)', value: 'bn-BD' },
  { name: 'Bengali (India)', value: 'bn-IN' },
  { name: 'Bulgarian (Bulgaria)', value: 'bg-BG' },
  { name: 'Burmese (Myanmar)', value: 'my-MM' },
  { name: 'Catalan (Spain)', value: 'ca-ES' },
  { name: 'Chinese, Cantonese (Traditional, Hong Kong)', value: 'yue-Hant-HK' },
  { name: 'Chinese, Mandarin (Simplified, China)', value: 'zh' },
  { name: 'Chinese, Mandarin (Simplified, Hong Kong)', value: 'zh-HK' },
  { name: 'Chinese, Mandarin (Simplified, Taiwan)', value: 'zh-TW' },
  { name: 'Croatian (Croatia)', value: 'hr-HR' },
  { name: 'Czech (Czech Republic)', value: 'cs-CZ' },
  { name: 'Danish (Denmark)', value: 'da-DK' },
  { name: 'Dutch (Belgium)', value: 'nl-BE' },
  { name: 'Dutch (Netherlands)', value: 'nl-NL' },
  { name: 'English (Australia)', value: 'en-AU' },
  { name: 'English (Canada)', value: 'en-CA' },
  { name: 'English (Ghana)', value: 'en-GH' },
  { name: 'English (India)', value: 'en-IN' },
  { name: 'English (Ireland)', value: 'en-IE' },
  { name: 'English (Kenya)', value: 'en-KE' },
  { name: 'English (New Zealand)', value: 'en-NZ' },
  { name: 'English (Nigeria)', value: 'en-NG' },
  { name: 'English (Philippines)', value: 'en-PH' },
  { name: 'English (Singapore)', value: 'en-SG' },
  { name: 'English (South Africa)', value: 'en-ZA' },
  { name: 'English (Tanzania)', value: 'en-TZ' },
  { name: 'English (United Kingdom)', value: 'en-GB' },
  { name: 'English (United States)', value: 'en-US' },
  { name: 'Estonian (Estonia)', value: 'et-EE' },
  { name: 'Filipino (Philippines)', value: 'fil-PH' },
  { name: 'Finnish (Finland)', value: 'fi-FI' },
  { name: 'French (Canada)', value: 'fr-CA' },
  { name: 'French (France)', value: 'fr-FR' },
  { name: 'Galician (Spain)', value: 'gl-ES' },
  { name: 'Georgian (Georgia)', value: 'ka-GE' },
  { name: 'German (Germany)', value: 'de-DE' },
  { name: 'Greek (Greece)', value: 'el-GR' },
  { name: 'Gujarati (India)', value: 'gu-IN' },
  { name: 'Hebrew (Israel)', value: 'he-IL' },
  { name: 'Hindi (India)', value: 'hi-IN' },
  { name: 'Hungarian (Hungary)', value: 'hu-HU' },
  { name: 'Icelandic (Iceland)', value: 'is-IS' },
  { name: 'Indonesian (Indonesia)', value: 'id-ID' },
  { name: 'Italian (Italy)', value: 'it-IT' },
  { name: 'Japanese (Japan)', value: 'ja-JP' },
  { name: 'Javanese (Indonesia)', value: 'jv-ID' },
  { name: 'Kannada (India)', value: 'kn-IN' },
  { name: 'Khmer (Cambodia)', value: 'km-KH' },
  { name: 'Korean (South Korea)', value: 'ko-KR' },
  { name: 'Lao (Laos)', value: 'lo-LA' },
  { name: 'Latvian (Latvia)', value: 'lv-LV' },
  { name: 'Lithuanian (Lithuania)', value: 'lt-LT' },
  { name: 'Macedonian (North Macedonia)', value: 'mk-MK' },
  { name: 'Malay (Malaysia)', value: 'ms-MY' },
  { name: 'Malayalam (India)', value: 'ml-IN' },
  { name: 'Marathi (India)', value: 'mr-IN' },
  { name: 'Mongolian (Mongolia)', value: 'mn-MN' },
  { name: 'Nepali (Nepal)', value: 'ne-NP' },
  { name: 'Norwegian Bokmål (Norway)', value: 'nb-NO' },
  { name: 'Persian (Iran)', value: 'fa-IR' },
  { name: 'Polish (Poland)', value: 'pl-PL' },
  { name: 'Portuguese (Brazil)', value: 'pt-BR' },
  { name: 'Portuguese (Portugal)', value: 'pt-PT' },
  { name: 'Punjabi (Gurmukhi, India)', value: 'pa-guru-IN' },
  { name: 'Romanian (Romania)', value: 'ro-RO' },
  { name: 'Russian (Russia)', value: 'ru-RU' },
  { name: 'Serbian (Serbia)', value: 'sr-RS' },
  { name: 'Sinhala (Sri Lanka)', value: 'si-LK' },
  { name: 'Slovak (Slovakia)', value: 'sk-SK' },
  { name: 'Slovenian (Slovenia)', value: 'sl-SI' },
  { name: 'Spanish (Argentina)', value: 'es-AR' },
  { name: 'Spanish (Bolivia)', value: 'es-BO' },
  { name: 'Spanish (Chile)', value: 'es-CL' },
  { name: 'Spanish (Colombia)', value: 'es-CO' },
  { name: 'Spanish (Costa Rica)', value: 'es-CR' },
  { name: 'Spanish (Dominican Republic)', value: 'es-DO' },
  { name: 'Spanish (Ecuador)', value: 'es-EC' },
  { name: 'Spanish (El Salvador)', value: 'es-SV' },
  { name: 'Spanish (Guatemala)', value: 'es-GT' },
  { name: 'Spanish (Honduras)', value: 'es-HN' },
  { name: 'Spanish (Mexico)', value: 'es-MX' },
  { name: 'Spanish (Nicaragua)', value: 'es-NI' },
  { name: 'Spanish (Panama)', value: 'es-PA' },
  { name: 'Spanish (Paraguay)', value: 'es-PY' },
  { name: 'Spanish (Peru)', value: 'es-PE' },
  { name: 'Spanish (Puerto Rico)', value: 'es-PR' },
  { name: 'Spanish (Spain)', value: 'es-ES' },
  { name: 'Spanish (United States)', value: 'es-US' },
  { name: 'Spanish (Uruguay)', value: 'es-UY' },
  { name: 'Spanish (Venezuela)', value: 'es-VE' },
  { name: 'Sundanese (Indonesia)', value: 'su-ID' },
  { name: 'Swahili (Kenya)', value: 'sw-KE' },
  { name: 'Swahili (Tanzania)', value: 'sw-TZ' },
  { name: 'Swedish (Sweden)', value: 'sv-SE' },
  { name: 'Tamil (India)', value: 'ta-IN' },
  { name: 'Tamil (Malaysia)', value: 'ta-MY' },
  { name: 'Tamil (Singapore)', value: 'ta-SG' },
  { name: 'Tamil (Sri Lanka)', value: 'ta-LK' },
  { name: 'Telugu (India)', value: 'te-IN' },
  { name: 'Thai (Thailand)', value: 'th-TH' },
  { name: 'Turkish (Turkey)', value: 'tr-TR' },
  { name: 'Ukrainian (Ukraine)', value: 'uk-UA' },
  { name: 'Urdu (India)', value: 'ur-IN' },
  { name: 'Urdu (Pakistan)', value: 'ur-PK' },
  { name: 'Uzbek (Uzbekistan)', value: 'uz-UZ' },
  { name: 'Vietnamese (Vietnam)', value: 'vi-VN' },
  { name: 'Zulu (South Africa)', value: 'zu-ZA' },
];
