module.exports = [
  {
    value: 'ar-XA',
    name: 'Arabic',
    voices: [
      { value: 'ar-XA-Standard-A', name: 'Standard-A (Female)' },
      { value: 'ar-XA-Standard-B', name: 'Standard-B (Male)' },
      { value: 'ar-XA-Standard-C', name: 'Standard-C (Male)' },
      { value: 'ar-XA-Standard-D', name: 'Standard-D (Female)' },
      { value: 'ar-XA-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'ar-XA-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'ar-XA-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'ar-XA-Wavenet-D', name: 'Wavenet-D (Female)' },
    ],
  },
  {
    value: 'af-ZA',
    name: 'Afrikaans (South Africa)',
    voices: [{ value: 'af-ZA-Standard-A', name: 'Standard-A (Female)' }],
  },
  {
    value: 'bn-IN',
    name: 'Bengali (India)',
    voices: [
      { value: 'bn-IN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'bn-IN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'bn-IN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'bn-IN-Wavenet-B', name: 'Wavenet-B (Male)' },
    ],
  },
  {
    value: 'bg-BG',
    name: 'Bulgarian (Bulgaria)',
    voices: [{ value: 'bg-BG-Standard-A', name: 'Standard-A (Female)' }],
  },
  {
    value: 'ca-ES',
    name: 'Catalan (Spain)',
    voices: [{ value: 'ca-ES-Standard-A', name: 'Standard-A (Female)' }],
  },
  {
    value: 'cs-CZ',
    name: 'Czech (Czech Republic)',
    voices: [
      { value: 'cs-CZ-Standard-A', name: 'Standard-A (Female)' },
      { value: 'cs-CZ-Wavenet-A', name: 'Wavenet-A (Female)' },
    ],
  },
  {
    value: 'da-DK',
    name: 'Danish (Denmark)',
    voices: [
      { value: 'da-DK-Standard-A', name: 'Standard-A (Female)' },
      { value: 'da-DK-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'da-DK-Neural2-D', name: 'Neural2-D (Female)' },
      { value: 'da-DK-Neural2-F', name: 'Neural2-F (Male)' },

      { value: 'da-DK-Standard-C', name: 'Standard-C (Male)' },
      { value: 'da-DK-Standard-D', name: 'Standard-D (Female)' },
      { value: 'da-DK-Standard-E', name: 'Standard-E (Female)' },
      { value: 'da-DK-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'da-DK-Wavenet-D', name: 'Wavenet-D (Female)' },
      { value: 'da-DK-Wavenet-E', name: 'Wavenet-E (Female)' },
    ],
  },
  {
    value: 'eu-ES',
    name: 'Basque (Spain)',
    voices: [{ value: 'eu-ES-Standard-A', name: 'Standard-A (Female)' }],
  },
  {
    value: 'nl-NL',
    name: 'Dutch (Netherlands)',
    voices: [
      { value: 'nl-NL-Standard-A', name: 'Standard-A (Female)' },
      { value: 'nl-NL-Standard-B', name: 'Standard-B (Male)' },
      { value: 'nl-NL-Standard-C', name: 'Standard-C (Male)' },
      { value: 'nl-NL-Standard-D', name: 'Standard-D (Female)' },
      { value: 'nl-NL-Standard-E', name: 'Standard-E (Female)' },
      { value: 'nl-NL-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'nl-NL-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'nl-NL-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'nl-NL-Wavenet-D', name: 'Wavenet-D (Female)' },
      { value: 'nl-NL-Wavenet-E', name: 'Wavenet-E (Female)' },
    ],
  },
  {
    value: 'en-AU',
    name: 'English (Australia)',
    voices: [
      { value: 'en-AU-Standard-A', name: 'Standard-A (Female)' },
      { value: 'en-AU-Standard-B', name: 'Standard-B (Male)' },
      { value: 'en-AU-Standard-C', name: 'Standard-C (Female)' },
      { value: 'en-AU-Standard-D', name: 'Standard-D (Male)' },
      { value: 'en-AU-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'en-AU-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'en-AU-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'en-AU-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'en-AU-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'en-AU-Neural2-B', name: 'Neural2-B (Male)' },
      { value: 'en-AU-Neural2-C', name: 'Neural2-C (Female)' },
      { value: 'en-AU-Neural2-D', name: 'Neural2-D (Male)' },
      { value: 'en-AU-Polyglot-1', name: 'Polyglot-1 (Male)' },
      { value: 'en-AU-News-E', name: 'News-E (Female)' },
      { value: 'en-AU-News-F', name: 'News-F (Female)' },
      { value: 'en-AU-News-G', name: 'News-G (Male)' },
    ],
  },
  {
    value: 'en-IN',
    name: 'English (India)',
    voices: [
      { value: 'en-IN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'en-IN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'en-IN-Standard-C', name: 'Standard-C (Male)' },
      { value: 'en-IN-Standard-D', name: 'Standard-D (Female)' },
      { value: 'en-IN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'en-IN-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'en-IN-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'en-IN-Wavenet-D', name: 'Wavenet-D (Female)' },

      { value: 'en-IN-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'en-IN-Neural2-B', name: 'Neural2-B (Male)' },
      { value: 'en-IN-Neural2-C', name: 'Neural2-C (Male)' },
      { value: 'en-IN-Neural2-D', name: 'Neural2-D (Female)' },
    ],
  },
  {
    value: 'en-GB',
    name: 'English (UK)',
    voices: [
      { value: 'en-GB-Standard-A', name: 'Standard-A (Female)' },
      { value: 'en-GB-Standard-B', name: 'Standard-B (Male)' },
      { value: 'en-GB-Standard-C', name: 'Standard-C (Female)' },
      { value: 'en-GB-Standard-D', name: 'Standard-D (Male)' },
      { value: 'en-GB-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'en-GB-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'en-GB-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'en-GB-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'en-GB-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'en-GB-Neural2-B', name: 'Neural2-B (Male)' },
      { value: 'en-GB-Neural2-C', name: 'Neural2-C (Female)' },
      { value: 'en-GB-Neural2-D', name: 'Neural2-D (Male)' },
      { value: 'en-GB-Neural2-F', name: 'Neural2-F (Female)' },
      { value: 'en-GB-News-G', name: 'News-G (Female)' },
      { value: 'en-GB-News-H', name: 'News-H (Female)' },
      { value: 'en-GB-News-I', name: 'News-I (Female)' },
      { value: 'en-GB-News-J', name: 'News-J (Male)' },
      { value: 'en-GB-News-K', name: 'News-K (Male)' },
      { value: 'en-GB-News-L', name: 'News-L (Male)' },
      { value: 'en-GB-News-M', name: 'News-M (Male)' },

      { value: 'en-GB-Studio-B', name: 'Studio-B (Male)' },
      { value: 'en-GB-Studio-C', name: 'Studio-C (Female)' },
      { value: 'en-GB-Wavenet-F', name: 'Wavenet-F (Female)' },
      { value: 'en-GB-Standard-F', name: 'Standard-F (Female)' },
    ],
  },
  {
    value: 'en-US',
    name: 'English (US)',
    voices: [
      { value: 'en-US-Standard-B', name: 'Standard-B (Male)' },
      { value: 'en-US-Standard-C', name: 'Standard-C (Female)' },
      { value: 'en-US-Standard-D', name: 'Standard-D (Male)' },
      { value: 'en-US-Standard-E', name: 'Standard-E (Female)' },
      { value: 'en-US-Wavenet-A', name: 'Wavenet-A (Male)' },
      { value: 'en-US-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'en-US-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'en-US-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'en-US-Wavenet-E', name: 'Wavenet-E (Female)' },
      { value: 'en-US-Wavenet-F', name: 'Wavenet-F (Female)' },
      { value: 'en-US-Neural2-A', name: 'Neural2-A (Male)' },
      { value: 'en-US-Neural2-C', name: 'Neural2-C (Female)' },
      { value: 'en-US-Neural2-D', name: 'Neural2-D (Male)' },
      { value: 'en-US-Neural2-E', name: 'Neural2-E (Female)' },
      { value: 'en-US-Neural2-F', name: 'Neural2-F (Female)' },
      { value: 'en-US-Neural2-G', name: 'Neural2-G (Female)' },
      { value: 'en-US-Neural2-H', name: 'Neural2-H (Female)' },
      { value: 'en-US-Neural2-I', name: 'Neural2-I (Male)' },
      { value: 'en-US-Neural2-J', name: 'Neural2-J (Male)' },
      { value: 'en-US-Studio-M', name: 'Studio-M (Male)' },
      { value: 'en-US-Studio-O', name: 'Studio-M (Female)' },
      { value: 'en-US-Polyglot-1', name: 'Polyglot-1 (Male)' },
      { value: 'en-US-News-K', name: 'News-K (Female)' },
      { value: 'en-US-News-L', name: 'News-L (Female)' },
      { value: 'en-US-News-M', name: 'News-M (Male)' },
      { value: 'en-US-News-N', name: 'News-N (Male)' },

      { value: 'en-US-Standard-A', name: 'Standard-A (Male)' },
      { value: 'en-US-Standard-F', name: 'Standard-F (Female)' },
      { value: 'en-US-Standard-G', name: 'Standard-G (Female)' },
      { value: 'en-US-Standard-H', name: 'Standard-H (Female)' },
      { value: 'en-US-Standard-I', name: 'Standard-I (Male)' },
      { value: 'en-US-Standard-J', name: 'Standard-J (Male)' },
      { value: 'en-US-Wavenet-G', name: 'Wavenet-G (Female)' },
      { value: 'en-US-Wavenet-H', name: 'Wavenet-H (Female)' },
      { value: 'en-US-Wavenet-I', name: 'Wavenet-I (Male)' },
      { value: 'en-US-Wavenet-J', name: 'Wavenet-J (Male)' },
    ],
  },
  {
    value: 'fil-PH',
    name: 'Filipino (Philippines)',
    voices: [
      { value: 'fil-PH-Standard-A', name: 'Standard-A (Female)' },
      { value: 'fil-PH-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'fil-ph-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'fil-ph-Neural2-D', name: 'Neural2-A (Male)' },

      { value: 'fil-PH-Standard-B', name: 'Standard-B (Female)' },
      { value: 'fil-PH-Standard-C', name: 'Standard-C (Male)' },
      { value: 'fil-PH-Standard-D', name: 'Standard-D (Male)' },
      { value: 'fil-PH-Wavenet-B', name: 'Wavenet-B (Female)' },
      { value: 'fil-PH-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'fil-PH-Wavenet-D', name: 'Wavenet-D (Male)' },
    ],
  },
  {
    value: 'fi-FI',
    name: 'Finnish (Finland)',
    voices: [
      { value: 'fi-FI-Standard-A', name: 'Standard-A (Female)' },
      { value: 'fi-FI-Wavenet-A', name: 'Wavenet-A (Female)' },
    ],
  },
  {
    value: 'fr-CA',
    name: 'French (Canada)',
    voices: [
      { value: 'fr-CA-Standard-A', name: 'Standard-A (Female)' },
      { value: 'fr-CA-Standard-B', name: 'Standard-B (Male)' },
      { value: 'fr-CA-Standard-C', name: 'Standard-C (Female)' },
      { value: 'fr-CA-Standard-D', name: 'Standard-D (Male)' },
      { value: 'fr-CA-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'fr-CA-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'fr-CA-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'fr-CA-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'fr-CA-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'fr-CA-Neural2-B', name: 'Neural2-B (Male)' },
      { value: 'fr-CA-Neural2-C', name: 'Neural2-C (Female)' },
      { value: 'fr-CA-Neural2-D', name: 'Neural2-D (Male)' },
    ],
  },
  {
    value: 'fr-FR',
    name: 'French (France)',
    voices: [
      { value: 'fr-FR-Standard-A', name: 'Standard-A (Female)' },
      { value: 'fr-FR-Standard-B', name: 'Standard-B (Male)' },
      { value: 'fr-FR-Standard-C', name: 'Standard-C (Female)' },
      { value: 'fr-FR-Standard-D', name: 'Standard-D (Male)' },
      { value: 'fr-FR-Standard-E', name: 'Standard-E (Female)' },
      { value: 'fr-FR-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'fr-FR-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'fr-FR-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'fr-FR-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'fr-FR-Wavenet-E', name: 'Wavenet-E (Female)' },
      { value: 'fr-FR-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'fr-FR-Neural2-B', name: 'Neural2-B (Male)' },
      { value: 'fr-FR-Neural2-C', name: 'Neural2-C (Female)' },
      { value: 'fr-FR-Neural2-D', name: 'Neural2-D (Male)' },
      { value: 'fr-FR-Neural2-E', name: 'Neural2-E (Female)' },
      { value: 'fr-FR-Polyglot-1', name: 'Polyglot-1 (Male)' },

      { value: 'fr-FR-Studio-A', name: 'Studio-A (Female)' },
      { value: 'fr-FR-Studio-D', name: 'Studio-D (Male)' },
    ],
  },
  {
    value: 'de-DE',
    name: 'German (Germany)',
    voices: [
      { value: 'de-DE-Standard-A', name: 'Standard-A (Female)' },
      { value: 'de-DE-Standard-B', name: 'Standard-B (Male)' },
      { value: 'de-DE-Standard-E', name: 'Standard-E (Male)' },
      { value: 'de-DE-Standard-F', name: 'Standard-F (Female)' },
      { value: 'de-DE-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'de-DE-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'de-DE-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'de-DE-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'de-DE-Wavenet-E', name: 'Wavenet-E (Male)' },
      { value: 'de-DE-Wavenet-F', name: 'Wavenet-F (Female)' },
      { value: 'de-DE-Neural2-B', name: 'Neural2-B (Male)' },
      { value: 'de-DE-Neural2-C', name: 'Neural2-C (Female)' },
      { value: 'de-DE-Neural2-D', name: 'Neural2-D (Male)' },
      { value: 'de-DE-Neural2-F', name: 'Neural2-F (Female)' },
      { value: 'de-DE-Polyglot-1', name: 'Polyglot-1 (Male)' },

      { value: 'de-DE-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'de-DE-Standard-C', name: 'Standard-C (Female)' },
      { value: 'de-DE-Standard-D', name: 'Standard-D (Male)' },
      { value: 'de-DE-Studio-B', name: 'Studio-B (Male)' },
      { value: 'de-DE-Studio-C', name: 'Studio-C (Female)' },
    ],
  },
  {
    value: 'el-GR',
    name: 'Greek (Greece)',
    voices: [
      { value: 'el-GR-Standard-A', name: 'Standard-A (Female)' },
      { value: 'el-GR-Wavenet-A', name: 'Wavenet-A (Female)' },
    ],
  },

  {
    value: 'gl-ES',
    name: 'Galician (Spain)',
    voices: [{ value: 'gl-ES-Standard-A', name: 'Standard-A (Female)' }],
  },
  {
    value: 'gu-IN',
    name: 'Gujarati (India)',
    voices: [
      { value: 'gu-IN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'gu-IN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'gu-IN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'gu-IN-Wavenet-B', name: 'Wavenet-B (Male)' },
    ],
  },
  {
    value: 'he-IL',
    name: 'Hebrew (Israel)',
    voices: [
      { value: 'he-IL-Standard-A', name: 'Standard-A (Female)' },
      { value: 'he-IL-Standard-B', name: 'Standard-B (Male)' },
      { value: 'he-IL-Standard-C', name: 'Standard-C (Female)' },
      { value: 'he-IL-Standard-D', name: 'Standard-D (Male)' },
      { value: 'he-IL-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'he-IL-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'he-IL-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'he-IL-Wavenet-D', name: 'Wavenet-D (Male)' },
    ],
  },

  {
    value: 'hi-IN',
    name: 'Hindi (India)',
    voices: [
      { value: 'hi-IN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'hi-IN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'hi-IN-Standard-C', name: 'Standard-C (Male)' },
      { value: 'hi-IN-Standard-D', name: 'Standard-D (Female)' },
      { value: 'hi-IN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'hi-IN-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'hi-IN-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'hi-IN-Wavenet-D', name: 'Wavenet-D (Female)' },
      { value: 'hi-IN-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'hi-IN-Neural2-B', name: 'Neural2-B (Male)' },
      { value: 'hi-IN-Neural2-C', name: 'Neural2-C (Male)' },
      { value: 'hi-IN-Neural2-D', name: 'Neural2-D (Female)' },
    ],
  },
  {
    value: 'hu-HU',
    name: 'Hungarian (Hungary)',
    voices: [
      { value: 'hu-HU-Standard-A', name: 'Standard-A (Female)' },
      { value: 'hu-HU-Wavenet-A', name: 'Wavenet-A (Female)' },
    ],
  },
  {
    value: 'is-IS',
    name: 'Icelandic (Iceland)',
    voices: [{ value: 'is-IS-Standard-A', name: 'Standard-A (Female)' }],
  },
  {
    value: 'id-ID',
    name: 'Indonesian (Indonesia)',
    voices: [
      { value: 'id-ID-Standard-A', name: 'Standard-A (Female)' },
      { value: 'id-ID-Standard-B', name: 'Standard-B (Male)' },
      { value: 'id-ID-Standard-C', name: 'Standard-C (Male)' },
      { value: 'id-ID-Standard-D', name: 'Standard-D (Female)' },
      { value: 'id-ID-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'id-ID-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'id-ID-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'id-ID-Wavenet-D', name: 'Wavenet-D (Female)' },
    ],
  },
  {
    value: 'it-IT',
    name: 'Italian (Italy)',
    voices: [
      { value: 'it-IT-Standard-A', name: 'Standard-A (Female)' },
      { value: 'it-IT-Standard-B', name: 'Standard-B (Female)' },
      { value: 'it-IT-Standard-C', name: 'Standard-C (Male)' },
      { value: 'it-IT-Standard-D', name: 'Standard-D (Male)' },
      { value: 'it-IT-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'it-IT-Wavenet-B', name: 'Wavenet-B (Female)' },
      { value: 'it-IT-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'it-IT-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'it-IT-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'it-IT-Neural2-C', name: 'Neural2-C (Male)' },
    ],
  },
  {
    value: 'ja-JP',
    name: 'Japanese (Japan)',
    voices: [
      { value: 'ja-JP-Standard-A', name: 'Standard-A (Female)' },
      { value: 'ja-JP-Standard-B', name: 'Standard-B (Female)' },
      { value: 'ja-JP-Standard-C', name: 'Standard-C (Male)' },
      { value: 'ja-JP-Standard-D', name: 'Standard-D (Male)' },
      { value: 'ja-JP-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'ja-JP-Wavenet-B', name: 'Wavenet-B (Female)' },
      { value: 'ja-JP-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'ja-JP-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'ja-JP-Neural2-B', name: 'Neural2-B (Female)' },
      { value: 'ja-JP-Neural2-C', name: 'Neural2-C (Male)' },
      { value: 'ja-JP-Neural2-D', name: 'Neural2-D (Male)' },
    ],
  },
  {
    value: 'kn-IN',
    name: 'Kannada (India)',
    voices: [
      { value: 'kn-IN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'kn-IN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'kn-IN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'kn-IN-Wavenet-B', name: 'Wavenet-B (Male)' },
    ],
  },
  {
    value: 'ko-KR',
    name: 'Korean (South Korea)',
    voices: [
      { value: 'ko-KR-Standard-A', name: 'Standard-A (Female)' },
      { value: 'ko-KR-Standard-B', name: 'Standard-B (Female)' },
      { value: 'ko-KR-Standard-C', name: 'Standard-C (Male)' },
      { value: 'ko-KR-Standard-D', name: 'Standard-D (Male)' },
      { value: 'ko-KR-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'ko-KR-Wavenet-B', name: 'Wavenet-B (Female)' },
      { value: 'ko-KR-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'ko-KR-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'ko-KR-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'ko-KR-Neural2-B', name: 'Neural2-B (Female)' },
      { value: 'ko-KR-Neural2-C', name: 'Neural2-C (Male)' },
    ],
  },
  {
    value: 'lv-LV',
    name: 'Latvian (Latvia)',
    voices: [{ value: 'lv-LV-Standard-A', name: 'Standard-A (Male)' }],
  },
  {
    value: 'lt-LT',
    name: 'Lithuanian (Lithuania)',
    voices: [{ value: 'lt-LT-Standard-A', name: 'Standard-A (Male)' }],
  },
  {
    value: 'cmn-CN',
    name: 'Mandarin Chinese',
    voices: [
      { value: 'cmn-CN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'cmn-CN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'cmn-CN-Standard-C', name: 'Standard-C (Male)' },
      { value: 'cmn-CN-Standard-D', name: 'Standard-D (Female)' },
      { value: 'cmn-CN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'cmn-CN-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'cmn-CN-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'cmn-CN-Wavenet-D', name: 'Wavenet-D (Female)' },
    ],
  },
  {
    value: 'cmn-TW',
    name: 'Mandarin Chinese (Traditional)',
    voices: [
      { value: 'cmn-TW-Standard-A-Alpha', name: 'Standard-A-Alpha (Female)' },
      { value: 'cmn-TW-Standard-B-Alpha', name: 'Standard-B-Alpha (Male)' },
      { value: 'cmn-TW-Standard-C-Alpha', name: 'Standard-C-Alpha (Male)' },
      { value: 'cmn-TW-Wavenet-A-Alpha', name: 'Wavenet-A-Alpha (Female)' },
      { value: 'cmn-TW-Wavenet-B-Alpha', name: 'Wavenet-B-Alpha (Male)' },
      { value: 'cmn-TW-Wavenet-C-Alpha', name: 'Wavenet-C-Alpha (Male)' },
    ],
  },
  {
    value: 'ms-MY',
    name: 'Malay (Malaysia)',
    voices: [
      { value: 'ms-MY-Standard-A', name: 'Standard-A (Female)' },
      { value: 'ms-MY-Standard-B', name: 'Standard-B (Male)' },
      { value: 'ms-MY-Standard-C', name: 'Standard-C (Female)' },
      { value: 'ms-MY-Standard-D', name: 'Standard-D (Male)' },
      { value: 'ms-MY-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'ms-MY-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'ms-MY-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'ms-MY-Wavenet-D', name: 'Wavenet-D (Male)' },
    ],
  },

  {
    value: 'ml-IN',
    name: 'Malayalam (India)',
    voices: [
      { value: 'ml-IN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'ml-IN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'ml-IN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'ml-IN-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'ml-IN-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'ml-IN-Wavenet-D', name: 'Wavenet-D (Male)' },
    ],
  },

  {
    value: 'mr-IN',
    name: 'Marathi (India)',
    voices: [
      { value: 'mr-IN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'mr-IN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'mr-IN-Standard-C', name: 'Standard-C (Female)' },
      { value: 'mr-IN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'mr-IN-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'mr-IN-Wavenet-C', name: 'Wavenet-C (Female)' },
    ],
  },

  {
    value: 'nb-NO',
    name: 'Norwegian (Norway)',
    voices: [
      { value: 'nb-NO-Standard-A', name: 'Standard-A (Female)' },
      { value: 'nb-NO-Standard-B', name: 'Standard-B (Male)' },
      { value: 'nb-NO-Standard-C', name: 'Standard-C (Female)' },
      { value: 'nb-NO-Standard-D', name: 'Standard-D (Male)' },
      { value: 'nb-no-Standard-E', name: 'Standard-E (Female)' },
      { value: 'nb-NO-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'nb-NO-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'nb-NO-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'nb-NO-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'nb-no-Wavenet-E', name: 'Wavenet-E (Female)' },
    ],
  },

  {
    value: 'nl-BE',
    name: 'Dutch (Belgium)',
    voices: [
      { value: 'nl-BE-Standard-A', name: 'Standard-A (Female)' },
      { value: 'nl-BE-Standard-B', name: 'Standard-B (Male)' },
      { value: 'nl-BE-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'nl-BE-Wavenet-B', name: 'Wavenet-B (Male)' },
    ],
  },

  {
    value: 'pl-PL',
    name: 'Polish (Poland)',
    voices: [
      { value: 'pl-PL-Standard-A', name: 'Standard-A (Female)' },
      { value: 'pl-PL-Standard-B', name: 'Standard-B (Male)' },
      { value: 'pl-PL-Standard-C', name: 'Standard-C (Male)' },
      { value: 'pl-PL-Standard-D', name: 'Standard-D (Female)' },
      { value: 'pl-PL-Standard-E', name: 'Standard-E (Female)' },
      { value: 'pl-PL-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'pl-PL-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'pl-PL-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'pl-PL-Wavenet-D', name: 'Wavenet-D (Female)' },
      { value: 'pl-PL-Wavenet-E', name: 'Wavenet-E (Female)' },
    ],
  },

  {
    value: 'pa-IN',
    name: 'Punjabi (India)',
    voices: [
      { value: 'pa-IN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'pa-IN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'pa-IN-Standard-C', name: 'Standard-C (Female)' },
      { value: 'pa-IN-Standard-D', name: 'Standard-D (Male)' },
      { value: 'pa-IN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'pa-IN-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'pa-IN-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'pa-IN-Wavenet-D', name: 'Wavenet-D (Male)' },
    ],
  },

  {
    value: 'pt-BR',
    name: 'Portuguese (Brazil)',
    voices: [
      { value: 'pt-BR-Standard-A', name: 'Standard-A (Female)' },
      { value: 'pt-BR-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'pt-BR-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'pt-BR-Neural2-B', name: 'Neural2-B (Male)' },
      { value: 'pt-BR-Neural2-C', name: 'Neural2-C (Female)' },

      { value: 'pt-BR-Standard-B', name: 'Standard-B (Male)' },
      { value: 'pt-BR-Standard-C', name: 'Standard-C (Female)' },
      { value: 'pt-BR-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'pt-BR-Wavenet-C', name: 'Wavenet-C (Female)' },
    ],
  },

  {
    value: 'pt-PT',
    name: 'Portuguese (Portugal)',
    voices: [
      { value: 'pt-PT-Standard-A', name: 'Standard-A (Female)' },
      { value: 'pt-PT-Standard-B', name: 'Standard-B (Male)' },
      { value: 'pt-PT-Standard-C', name: 'Standard-C (Male)' },
      { value: 'pt-PT-Standard-D', name: 'Standard-D (Female)' },
      { value: 'pt-PT-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'pt-PT-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'pt-PT-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'pt-PT-Wavenet-D', name: 'Wavenet-D (Female)' },
    ],
  },

  {
    value: 'ro-RO',
    name: 'Romanian (Romania)',
    voices: [
      { value: 'ro-RO-Standard-A', name: 'Standard-A (Female)' },
      { value: 'ro-RO-Wavenet-A', name: 'Wavenet-A (Female)' },
    ],
  },

  {
    value: 'ru-RU',
    name: 'Russian (Russia)',
    voices: [
      { value: 'ru-RU-Standard-A', name: 'Standard-A (Female)' },
      { value: 'ru-RU-Standard-B', name: 'Standard-B (Male)' },
      { value: 'ru-RU-Standard-C', name: 'Standard-C (Female)' },
      { value: 'ru-RU-Standard-D', name: 'Standard-D (Male)' },
      { value: 'ru-RU-Standard-E', name: 'Standard-E (Female)' },
      { value: 'ru-RU-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'ru-RU-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'ru-RU-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'ru-RU-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'ru-RU-Wavenet-E', name: 'Wavenet-E (Female)' },
    ],
  },

  {
    value: 'sk-SK',
    name: 'Slovak (Slovakia)',
    voices: [
      { value: 'sk-SK-Standard-A', name: 'Standard-A (Female)' },
      { value: 'sk-SK-Wavenet-A', name: 'Wavenet-A (Female)' },
    ],
  },

  {
    value: 'sr-RS',
    name: 'Serbian (Cyrillic)',
    voices: [{ value: 'sr-RS-Standard-A', name: 'Standard-A (Female)' }],
  },

  {
    value: 'es-ES',
    name: 'Spanish (Spain)',
    voices: [
      { value: 'es-ES-Standard-A', name: 'Standard-A (Female)' },
      { value: 'es-ES-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'es-ES-Neural2-B', name: 'Neural2-B (Male)' },
      { value: 'es-ES-Neural2-C', name: 'Neural2-C (Female)' },
      { value: 'es-ES-Neural2-D', name: 'Neural2-D (Female)' },
      { value: 'es-ES-Neural2-E', name: 'Neural2-E (Female)' },
      { value: 'es-ES-Neural2-F', name: 'Neural2-F (Male)' },
      { value: 'es-ES-Polyglot-1', name: 'Polyglot-1 (Male)' },

      { value: 'es-ES-Standard-B', name: 'Standard-B (Male)' },
      { value: 'es-ES-Standard-C', name: 'Standard-C (Female)' },
      { value: 'es-ES-Standard-D', name: 'Standard-D (Female)' },
      { value: 'es-ES-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'es-ES-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'es-ES-Wavenet-D', name: 'Wavenet-D (Female)' },
    ],
  },
  {
    value: 'es-US',
    name: 'Spanish (US)',
    voices: [
      { value: 'es-US-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'es-US-Neural2-B', name: 'Neural2-B (Male)' },
      { value: 'es-US-Neural2-C', name: 'Neural2-C (Male)' },
      { value: 'es-US-Studio-B', name: 'Studio-B (Male)' },
      { value: 'es-US-Polyglot-1', name: 'Polyglot-1 (Male)' },
      { value: 'es-US-News-D', name: 'News-D (Male)' },
      { value: 'es-US-News-E', name: 'News-E (Male)' },
      { value: 'es-US-News-F', name: 'News-F (Female)' },
      { value: 'es-US-News-G', name: 'News-G (Female)' },

      { value: 'es-US-Standard-A', name: 'Standard-A (Female)' },
      { value: 'es-US-Standard-B', name: 'Standard-B (Male)' },
      { value: 'es-US-Standard-C', name: 'Standard-C (Male)' },
      { value: 'es-US-Studio-B', name: 'Studio-B (Male)' },
      { value: 'es-US-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'es-US-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'es-US-Wavenet-C', name: 'Wavenet-C (Male)' },
    ],
  },
  {
    value: 'sv-SE',
    name: 'Swedish (Sweden)',
    voices: [
      { value: 'sv-SE-Standard-A', name: 'Standard-A (Female)' },
      { value: 'sv-SE-Wavenet-A', name: 'Wavenet-A (Female)' },

      { value: 'sv-SE-Standard-B', name: 'Standard-B (Female)' },
      { value: 'sv-SE-Standard-C', name: 'Standard-C (Female)' },
      { value: 'sv-SE-Standard-D', name: 'Standard-D (Male)' },
      { value: 'sv-SE-Standard-E', name: 'Standard-E (Male)' },
      { value: 'sv-SE-Wavenet-B', name: 'Wavenet-B (Female)' },
      { value: 'sv-SE-Wavenet-C', name: 'Wavenet-C (Male)' },
      { value: 'sv-SE-Wavenet-D', name: 'Wavenet-D (Female)' },
      { value: 'sv-SE-Wavenet-E', name: 'Wavenet-E (Male)' },
    ],
  },

  {
    value: 'ta-IN',
    name: 'Tamil (India)',
    voices: [
      { value: 'ta-IN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'ta-IN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'ta-IN-Standard-C', name: 'Standard-C (Female)' },
      { value: 'ta-IN-Standard-D', name: 'Standard-D (Male)' },
      { value: 'ta-IN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'ta-IN-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'ta-IN-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'ta-IN-Wavenet-D', name: 'Wavenet-D (Male)' },
    ],
  },

  {
    value: 'te-IN',
    name: 'Telugu (India)',
    voices: [
      { value: 'te-IN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'te-IN-Standard-B', name: 'Standard-B (Male)' },
    ],
  },

  {
    value: 'tr-TR',
    name: 'Turkish (Turkey)',
    voices: [
      { value: 'tr-TR-Standard-A', name: 'Standard-A (Female)' },
      { value: 'tr-TR-Standard-B', name: 'Standard-B (Male)' },
      { value: 'tr-TR-Standard-C', name: 'Standard-C (Female)' },
      { value: 'tr-TR-Standard-D', name: 'Standard-D (Female)' },
      { value: 'tr-TR-Standard-E', name: 'Standard-E (Male)' },
      { value: 'tr-TR-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'tr-TR-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'tr-TR-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'tr-TR-Wavenet-D', name: 'Wavenet-D (Female)' },
      { value: 'tr-TR-Wavenet-E', name: 'Wavenet-E (Male)' },
    ],
  },
  {
    value: 'uk-UA',
    name: 'Ukrainian (Ukraine)',
    voices: [
      { value: 'uk-UA-Standard-A', name: 'Standard-A (Female)' },
      { value: 'uk-UA-Wavenet-A', name: 'Wavenet-A (Female)' },
    ],
  },
  {
    value: 'th-TH',
    name: 'Thai (Thailand)',
    voices: [
      { value: 'th-TH-Neural2-C', name: 'Neural2-C (Female)' },

      { value: 'th-TH-Standard-A', name: 'Standard-A (Female)' },
    ],
  },
  {
    value: 'vi-VN',
    name: 'Vietnamese (Vietnam)',
    voices: [
      { value: 'vi-VN-Standard-A', name: 'Standard-A (Female)' },
      { value: 'vi-VN-Standard-B', name: 'Standard-B (Male)' },
      { value: 'vi-VN-Standard-C', name: 'Standard-C (Female)' },
      { value: 'vi-VN-Standard-D', name: 'Standard-D (Male)' },
      { value: 'vi-VN-Wavenet-A', name: 'Wavenet-A (Female)' },
      { value: 'vi-VN-Wavenet-B', name: 'Wavenet-B (Male)' },
      { value: 'vi-VN-Wavenet-C', name: 'Wavenet-C (Female)' },
      { value: 'vi-VN-Wavenet-D', name: 'Wavenet-D (Male)' },
      { value: 'vi-VN-Neural2-A', name: 'Neural2-A (Female)' },
      { value: 'vi-VN-Neural2-D', name: 'Neural2-D (Male)' },
    ],
  },
  {
    value: 'yue-HK',
    name: 'Chinese (Hong Kong)',
    voices: [
      { value: 'yue-HK-Standard-A', name: 'Standard-A (Female)' },
      { value: 'yue-HK-Standard-B', name: 'Standard-B (Male)' },
      { value: 'yue-HK-Standard-C', name: 'Standard-C (Female)' },
      { value: 'yue-HK-Standard-D', name: 'Standard-D (Male)' },
    ],
  },
];
