module.exports = [
  {
    value: 'en',
    name: 'English',
    voices: [
      { name: 'Alex', value: 'Alex' },
      { name: 'Ashley', value: 'Ashley' },
      { name: 'Craig', value: 'Craig' },
      { name: 'Deborah', value: 'Deborah' },
      { name: 'Dennis', value: 'Dennis' },
      { name: 'Edward', value: 'Edward' },
      { name: 'Elizabeth', value: 'Elizabeth' },
      { name: 'Hades', value: 'Hades' },
      { name: 'Julia', value: 'Julia' },
      { name: 'Pixie', value: 'Pixie' },
      { name: 'Mark', value: 'Mark' },
      { name: 'Olivia', value: 'Olivia' },
      { name: 'Priya', value: 'Priya' },
      { name: 'Ronald', value: 'Ronald' },
      { name: 'Sarah', value: 'Sarah' },
      { name: 'Shaun', value: 'Shaun' },
      { name: 'Theodore', value: 'Theodore' },
      { name: 'Timothy', value: 'Timothy' },
      { name: 'Wendy', value: 'Wendy' },
      { name: 'Dominus', value: 'Dominus' },
    ],
  },
];
